### PR TITLE
Added know your officers section

### PR DESCRIPTION
**Pull request by Pixelazation**
Desktop layout is more or less the same with a slightly different ratio between image and text. Edited layout for mobile to make it one column. What you guys think?

Desktop:
image

Mobile:
image

### CODE REVIEW

**Comment by maxellmilay** [comment]
@Pixelazation it seem that the image on other sizes of the viewport is stretched. Kindly find a way around that, thanks!
image

**Comment by Pixelazation** [comment]
image
Maintained original img aspect ratio and added blurred background. What do you think? @maxellmilay

**Comment by maxellmilay** [comment]
@Pixelazation would it be too small if we just maintain the original aspect ratio for the whole thing all the way to mobile?

**Comment by Pixelazation** [comment]
> @Pixelazation would it be too small if we just maintain the original aspect ratio for the whole thing all the way to mobile?

Image itself is already the original ratio in mobile, but if you mean the layout, I tried editing it and the image seems quite small still even with the text scaled down.

image

**Comment by Pixelazation** [comment]
Adjusted fonts and added padding @maxellmilay 

https://github.com/user-attachments/assets/e176dae2-9574-4f59-a77f-b5d0b824368d

**Review by maxellmilay — APPROVED** [review]
@Pixelazation  LGTM :fire:

**Pull request merged**
