### PR TITLE
Feature/create scholarship and student opportunities section

### LINKED ISSUE #5: Create scholarship & student opportunities section
image

### PR DESCRIPTION
**Pull request by lssndrrr**
added scholarship section

https://github.com/user-attachments/assets/312d43ee-ba05-4eb1-9531-01cd1e607b4b

on small screens, image is placed on top of the section, added a few breakpoints for font sizes as well as centered the text

closes #5

### CODE REVIEW

**Comment by maxellmilay** [comment]
@lssndrrr responsivenss is broken. When dealing with mobile responsivness, always consider the smallest viewport as 320px
image

This should not be a circle
image

Text is not scaled down for mobile
image

**Comment by maxellmilay** [comment]
@lssndrrr I also noticed in the video that you shrinked the browser. You can do `Ctrl` + `Shift` + `I` to modify the viewport dimensions

**Comment by maxellmilay** [comment]
@lssndrrr kindly pull first before making any changes. I updated you branch with the latest changes

**Comment by lssndrrr** [comment]
https://github.com/user-attachments/assets/5a62e568-89ea-4da0-a41d-f073a89399e2

responsiveness should be fixed, unless i missed something. the smallest viewport would partially hide the 'opportunities' part, but if sized down, it won't match with the other sections. if matching isn't required, or if there are any other changes, let me know :)

**Review by maxellmilay — APPROVED** [review]
@lssndrrr LGTM :fire:

**Pull request merged**
