### PR TITLE
[Arwin][UI] added navigation bar template

### PR DESCRIPTION
**Pull request by arwin50**
https://github.com/user-attachments/assets/da3953fa-a0fc-46d8-b4ba-7efb17de274c

what do you think guys?

### CODE REVIEW

**Comment by maxellmilay** [comment]
@arwin50 Nice job! But I forgot to tell you that we will remove the navbar part HAHAHAHA. Retain the logo and name, and center it hehe

**Comment by maxellmilay** [comment]
image
Something like this instead @arwin50

**Comment by arwin50** [comment]
image

@maxellmilay  what do you think?

**Review by maxellmilay — APPROVED** [review]
@arwin50 LGTM :fire:

**Pull request merged**
