### PR TITLE
[Feature][Louise] added merch card, merch grid, merch filters components

### PR DESCRIPTION
**Pull request by Loweso**
merch card:
- can work with props
- working color swap
- add to cart and heart doesnt do anything yet lmao

merch grid
- also contains button to jump to filters section
- ❗ component code contains test data

filters
- fully frontend, pressing Apply Filters actually isnt coded to do anything yet lmao

image
mobile:
image
image

### CODE REVIEW

**Comment by Loweso** [comment]
eyy ka muna eyy 🤙🤙🤙

**Comment by maxellmilay** [comment]
@Loweso when the viewport is 1032 px, the cards are squashed
image

Maybe we can try the suggestion of a the filter being a fixed sidebar that can be toggled?

**Comment by maxellmilay** [comment]
@Loweso In addition, the cards also are squashed vertically when the viewport width is 906px
image

Let's try to make the card dimension aspect ratio the same as possible to avoid this issue

**Comment by Loweso** [comment]
@maxellmilay
merch card:
- adjusted sizes
merch filters:
- sidebar that can be hidden
- allows space for sponsors component

image
image
other viewports:
image
image
image
image

**Review by maxellmilay — APPROVED** [review]
@Loweso LGTM :fire:

**Pull request merged**
