### PR TITLE
Feature/create recent news and announcements section

### PR DESCRIPTION
**Pull request by JGEPT**
https://github.com/user-attachments/assets/f4c1951f-e56f-499b-bf03-3b624114171a

Added the header, and the basic card grid for the different news and announcements. The font and image are still place holders. Made it so that the grid is responsive and will reduce the number of columns depending on the screen size. Added the see more/see less button to toggle between expanding and collapsing the grid. Also tweaked the header width as it would have an overflow whenever a page had a scrollbar. Routed the learn button to the edev page.

### CODE REVIEW

**Comment by maxellmilay** [comment]
@JGEPT well done! I really like the transition from `framer-motion`, but the mobile viewport seems to have responsive issues
image

When testing for mobile perspective, make sure the viewport width is 320px. This can be done by click the smallest rectangle here right below the dimensions
image

**Comment by maxellmilay** [comment]
@JGEPT I also noticed that when the viewport is 778px, the grid does not have any horizontal padding, resulting the leftmost and rightmost cards to be pushed to the edges. Let's try to make the padding responsive
image

**Comment by maxellmilay** [comment]
@JGEPT I also think my instructions for the components were not clear, my bad. The `AnnouncementCard.tsx` component is only for an individual card like this:
image

You can then create another component (maybe call it `AnnoucementSection.tsx`) where you map the cards using the card component you just created

**Comment by JGEPT** [comment]
https://github.com/user-attachments/assets/38494446-1310-4bc7-9de0-27e770dd168e

Tweaked the padding for when the viewport is 778px. Also tweaked the mobile view to fit better. Separated the card itself into AnnouncementCard and the entire section to AnnouncementSection as commented. Also tweaked the colors to use the present palette.

**Comment by maxellmilay** [comment]
@JGEPT It looks good now. Just one final thing. Let's have 1 card in the mobile version instead since it looks really squished
image

**Review by maxellmilay — APPROVED** [review]
@JGEPT LGTM :fire:

**Pull request merged**
