### PR TITLE
Feature/sidepanel component

### PR DESCRIPTION
**Pull request by JGEPT**
Added the initial sidebar, added the slide in, slide out, hover animations. Tweaked the responsiveness of the side to make it more mobile friendly. Adjusted the side bar to appear on top, and not shift elements when it slides in. Adjusted it so that the sidebar is not open by default

https://github.com/user-attachments/assets/b5c96a02-c625-499c-b573-1f7d0f7dc90e

### CODE REVIEW

**Comment by maxellmilay** [comment]
@JGEPT let's move the entire side panel code into another component. It can be named `AdminSidePanel`, where `<AdminSidePanel/>` can be placed inside the dashboard page instead

**Review by maxellmilay — CHANGES_REQUESTED** [review]
kindly resolve my comments

**Comment by JGEPT** [comment]
Created a dedicated component for the admin side panel.


https://github.com/user-attachments/assets/5c2a9418-6d6e-467e-b0e8-12da3a6d439d

**Review by maxellmilay — APPROVED** [review]
@JGEPT LGTM :fire:

**Pull request merged**
